version: '3'
services:
  nexus:
    environment:
      - "VIRTUAL_HOST=domain_name"
      - "VIRTUAL_PORT=8081"
    volumes:
      - /opt/services/nexus:/nexus-data
      - /opt/services/deploy:/opt/sonatype/nexus/deploy
    ports:
      - "8081:8081"
      - "8082:8082"
    image: sonatype/nexus3:3.52.0
    restart: unless-stopped
    container_name: nexus3
    networks:
      - services_net

  nginx-proxy:
    image: jwilder/nginx-proxy
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /opt/services/certs:/etc/nginx/certs
      - /etc/hosts:/etc/hosts
      - /opt/services/conf/nginx.conf:/etc/nginx/nginx.conf
    restart: unless-stopped
    container_name: nginx-proxy
    networks:
      - services_net

networks:
  services_net:
    driver: bridge
